language: java

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

matrix:
  include:
# Java 9 (openjdk-9.0.1 fails with java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)
    - jdk: oraclejdk9
      env: JDK_RELEASE='JDK 9'
      install: echo "Don't let Travis CI execute './gradlew assemble' by default"
# Java 10
    - env: JDK_RELEASE='JDK 10 Early-Access'
      install: . ./src/install/install-jdk-10.sh

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version
# Build JUnit 5
  - ./gradlew build --scan --stacktrace -Dkotlin.compiler.execution.strategy="in-process"
# Run benchmarks
  - ./gradlew :platform-tests:jmh

# Do not store unnecessary files from Gradle dependency cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Store Gradle dependency cache and Gradle Wrapper files for next execution
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Run clover report and send report to codecov after build success for JDK 9 builds
after_success:
  - test "$JDK_RELEASE" = "JDK 9" && ./gradlew -PenableClover clean cloverXmlReport || true
  - test "$JDK_RELEASE" = "JDK 9" && bash <(curl -s https://codecov.io/bash) || true
