language: java

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

# Get latest install-jdk.sh script
before_install:
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

matrix:
  include:
# Java 9 "Oracle JDK" (provided by Travis CI)
    - jdk: oraclejdk9
      env: JDK='Oracle JDK 9' EXTRA_GRADLE_ARGS='-PenableJaCoCo'
      install: echo "Don't let Travis CI execute './gradlew assemble' by default"
# Java 10 "Oracle JDK" (not yet provided by Travis CI)
    - jdk: oraclejdk10
      env: JDK='Oracle JDK 10'
      install: echo "Don't let Travis CI execute './gradlew assemble' by default"
# Java 10 "Oracle JDK"
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL
# Java 11 "Oracle JDK"
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
# The following environments are known to fail
  allow_failures:
    - env: JDK='Oracle JDK 10'
    - env: JDK='Oracle JDK 11'

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version
# Build JUnit 5
  - ./gradlew --scan --stacktrace --warning-mode=all ${EXTRA_GRADLE_ARGS} build

# Run JaCoCo report and send report to codecov.io after build success for JDK 9 build
after_success:
  - test "${JDK}" = "Oracle JDK 9" && ./gradlew -PenableJaCoCo jacocoRootReport || true
  - test "${JDK}" = "Oracle JDK 9" && bash <(curl -s https://codecov.io/bash) || true
