language: java
sudo: false
dist: trusty

env:
  - _JAVA_OPTIONS='-Xmx500m'

matrix:
  include:
    - jdk: oraclejdk8 # JDK 1.8.0_131-b11
    - jdk: oraclejdk9 # JDK 9-ea+174 provided by Travis will be replaced by 9+178 in "before_install"
      before_install:
        - cd ~
        - wget http://download.java.net/java/jdk9/archive/178/binaries/jdk-9+178_linux-x64_bin.tar.gz
        - tar -xzf jdk-9+178_linux-x64_bin.tar.gz
        - export JAVA_HOME=~/jdk-9
        - PATH=$JAVA_HOME/bin:$PATH
        - cd -

# Don't let Travis CI execute './gradlew assemble' by default
install:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version

script:
  - ./gradlew build --scan
