language: java

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

matrix:
  include:
# Java 9 (openjdk-9.0.1 fails with java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)
    - jdk: oraclejdk9
      env: JDK_RELEASE='JDK 9'
      install: echo "Don't let Travis CI execute './gradlew assemble' by default"
# Java 10
    - env: JDK_RELEASE='JDK 10 Early-Access'
      install: . ./src/install/install-jdk-10.sh
  allow_failures:
    - env: JDK_RELEASE='JDK 10 Early-Access'

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version
# Build JUnit 5
  - ./gradlew build --scan --stacktrace -Dkotlin.compiler.execution.strategy="in-process"
