# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JUnit 5
email: team@junit.org
baseurl: "/junit5" # the subpath of your site, e.g. /blog
url: "http://junit.org" # the base hostname & protocol for your site
twitter_username: junitteam
github_username:  junit-team
repository: junit-team.github.io

# Build settings
markdown: kramdown

exclude:
- faq.md
