#type: specs.openrewrite.org/v1beta/recipe
#name: org.junit.openrewrite.recipe.CodeCleanup
#displayName: Code cleanup
#description: Automatically cleanup code, e.g. remove unnecessary parentheses, simplify expressions.
#recipeList:
#  - org.openrewrite.java.RemoveUnusedImports
#  - org.openrewrite.staticanalysis.EqualsAvoidsNull
#  - org.openrewrite.staticanalysis.ModifierOrder
#  - org.junit.openrewrite.recipe.AddLicenseHeader
#  - org.junit.openrewrite.recipe.Java21ForTests
#  - org.openrewrite.java.format.AutoFormat
#  - org.openrewrite.java.format.BlankLines
#  - org.openrewrite.java.format.NormalizeFormat
#  - org.openrewrite.java.format.NormalizeLineBreaks
#  - org.openrewrite.java.format.RemoveTrailingWhitespace
#  - org.openrewrite.java.format.Spaces
#  - org.openrewrite.java.format.TabsAndIndents
#  - org.openrewrite.java.format.WrappingAndBraces
#  - org.openrewrite.java.migrate.UpgradeToJava17
#  - org.openrewrite.java.testing.assertj.Assertj
#  - org.openrewrite.java.testing.cleanup.AssertTrueNullToAssertNull
#  - org.openrewrite.java.testing.cleanup.TestsShouldNotBePublic
#  - org.openrewrite.java.testing.junit5.JUnit5BestPractices
#  - org.openrewrite.staticanalysis.CodeCleanup
#  - org.openrewrite.staticanalysis.CommonStaticAnalysis
#  - org.openrewrite.staticanalysis.FinalizeLocalVariables
#  - org.openrewrite.staticanalysis.MissingOverrideAnnotation
#  - org.openrewrite.staticanalysis.RedundantFileCreation
#  - org.openrewrite.staticanalysis.RemoveUnusedLocalVariables
#  - org.openrewrite.staticanalysis.RemoveUnusedPrivateFields
#  - org.openrewrite.staticanalysis.RemoveUnusedPrivateMethods
#  - org.openrewrite.staticanalysis.StringLiteralEquality
#  - org.openrewrite.text.EndOfLineAtEndOfFile
#---
type: specs.openrewrite.org/v1beta/recipe
name: org.junit.openrewrite.recipe.AddLicenseHeader
displayName: AddLicenseHeader
recipeList:
  - org.openrewrite.java.AddLicenseHeader:
    licenseText: """
      /*
       * Copyright 2015-${CURRENT_YEAR} the original author or authors.
       *
       * All rights reserved. This program and the accompanying materials are
       * made available under the terms of the Eclipse Public License v2.0 which
       * accompanies this distribution and is available at
       *
       * https://www.eclipse.org/legal/epl-v20.html
       */
      """
---
type: specs.openrewrite.org/v1beta/recipe
name: org.junit.openrewrite.recipe.Java21ForTests
displayName: Java21ForTests
preconditions:
  - org.openrewrite.java.search.IsLikelyTest
recipeList:
  - org.openrewrite.java.migrate.UpgradeToJava21
---
type: specs.openrewrite.org/v1beta/style
name: org.junit.openrewrite.recipe.NoTabsNoStarImports
styleConfigs:
  - org.openrewrite.java.style.TabsAndIndentsStyle:
      useTabCharacter: false
  - org.openrewrite.java.style.ImportLayoutStyle:
      classCountToUseStarImport: 9999