[versions]
ant = "1.10.12"
apiguardian = "1.1.2"
asciidoctor-pdf = "1.5.3"
assertj = "3.23.1"
checkstyle = "9.0"
jacoco = "0.8.7"
jmh = "1.36"
junit4 = "4.13.2"
junit4Osgi = "4.13.2_1"
junit4Min = "4.12"
ktlint = "0.43.0"
log4j = "2.19.0"
opentest4j = "1.2.0"
openTestReporting = "0.1.0-M1"
surefire = "3.0.0-M7"
xmlunit = "2.9.0"

[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant" }
ant-junit = { module = "org.apache.ant:ant-junit", version.ref = "ant" }
ant-junitlauncher = { module = "org.apache.ant:ant-junitlauncher", version.ref = "ant" }
apiguardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version = "1.0.1" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bartholdy = { module = "de.sormuras:bartholdy", version = "0.2.3" }
bnd = { module = "biz.aQute.bnd:biz.aQute.bndlib", version = "6.4.0" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.153" }
commons-io = { module = "commons-io:commons-io", version = "2.11.0" }
groovy4 = { module = "org.apache.groovy:groovy", version = "4.0.7" }
groovy2-bom = { module = "org.codehaus.groovy:groovy-bom", version = "2.5.14" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "2.2" }
jfrunit = { module = "org.moditect.jfrunit:jfrunit-core", version = "1.0.0.Alpha2" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
joox = { module = "org.jooq:joox", version = "2.0.0" }
junit4 = { module = "junit:junit", version = { require = "[4.12,)", prefer = "4.13.2" } }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
maven = { module = "org.apache.maven:apache-maven", version = "3.8.6" }
mockito = { module = "org.mockito:mockito-junit-jupiter", version = "4.11.0" }
opentest4j = { module = "org.opentest4j:opentest4j", version.ref = "opentest4j" }
openTestReporting-events = { module = "org.opentest4j.reporting:open-test-reporting-events", version.ref = "openTestReporting" }
openTestReporting-tooling = { module = "org.opentest4j.reporting:open-test-reporting-tooling", version.ref = "openTestReporting" }
picocli = { module = "info.picocli:picocli", version = "4.7.0" }
slf4j-julBinding = { module = "org.slf4j:slf4j-jdk14", version = "2.0.6" }
spock1 = { module = "org.spockframework:spock-core", version = "1.3-groovy-2.5" }
univocity-parsers = { module = "com.univocity:univocity-parsers", version = "2.9.1" }
xmlunit-assertj = { module = "org.xmlunit:xmlunit-assertj3", version.ref = "xmlunit" }
xmlunit-placeholders = { module = "org.xmlunit:xmlunit-placeholders", version.ref = "xmlunit" }

[bundles]
ant = ["ant", "ant-junit", "ant-junitlauncher"]
log4j = ["log4j-core", "log4j-jul"]
xmlunit = ["xmlunit-assertj", "xmlunit-placeholders"]
