[versions]
apiguardian = "1.1.2"
asciidoctor-pdf = "1.5.3"
assertj = "3.21.0"
checkstyle = "9.0"
jacoco = "0.8.7"
jmh = "1.33"
junit4 = "4.13.2"
junit4Osgi = "4.13.2_1"
junit4Min = "4.12"
ktlint = "0.43.0"
log4j = "2.17.1"
opentest4j = "1.2.0"
surefire = "2.22.2"

[libraries]
apiguardian = { module = "org.apiguardian:apiguardian-api", version.ref = "apiguardian" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version = "0.22.0" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bartholdy = { module = "de.sormuras:bartholdy", version = "0.2.3" }
bnd = { module = "biz.aQute.bnd:biz.aQute.bndlib", version = "6.1.0" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.132" }
commons-io = { module = "commons-io:commons-io", version = "2.11.0" }
groovy4 = { module = "org.apache.groovy:groovy", version = "4.0.0-beta-1" }
groovy2-bom = { module = "org.codehaus.groovy:groovy-bom", version = "2.5.14" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "2.2" }
jfrunit = { module = "org.moditect.jfrunit:jfrunit-core", version = "1.0.0.Alpha2" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
joox = { module = "org.jooq:joox", version = "1.6.2" }
junit4 = { module = "junit:junit", version = { require = "[4.12,)", prefer = "4.13.2" } }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.4.3" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-jul = { module = "org.apache.logging.log4j:log4j-jul", version.ref = "log4j" }
mockito = { module = "org.mockito:mockito-junit-jupiter", version = "4.1.0" }
opentest4j = { module = "org.opentest4j:opentest4j", version.ref = "opentest4j" }
picocli = { module = "info.picocli:picocli", version = "4.6.2" }
slf4j-julBinding = { module = "org.slf4j:slf4j-jdk14", version = "1.7.32" }
spock1 = { module = "org.spockframework:spock-core", version = "1.3-groovy-2.5" }
univocity-parsers = { module = "com.univocity:univocity-parsers", version = "2.9.1" }

[bundles]
log4j = ["log4j-core", "log4j-jul"]
