blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/junit-team/junit-framework/discussions/categories/q-a
    about: Please ask and answer questions here
  - name: Ask a question (Stack Overflow)
    url: https://stackoverflow.com/questions/tagged/junit5
    about: Alternatively, ask questions here
