name: Cross-Version

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - '*'

env:
  ORG_GRADLE_PROJECT_enableTestDistribution: true
  ORG_GRADLE_PROJECT_junitBuildCacheUsername: ${{ secrets.BUILD_CACHE_USERNAME }}
  ORG_GRADLE_PROJECT_junitBuildCachePassword: ${{ secrets.BUILD_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [18]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Test JDK
        uses: ./.github/actions/setup-test-jdk
      - name: 'Download JDK ${{ matrix.jdk }}'
        id: download-jdk
        uses: sormuras/download-jdk@v1
        with:
          feature: '${{ matrix.jdk }}'
      - name: 'Set up JDK ${{ matrix.jdk }}'
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          java-version: '${{ steps.download-jdk.outputs.version }}'
          jdkFile: '${{ steps.download-jdk.outputs.file }}'
      - name: 'Prepare JDK${{ matrix.jdk }} env var'
        shell: bash
        run: echo "JDK${{ matrix.jdk }}=$JAVA_HOME" >> $GITHUB_ENV
      - name: Set up Gradle JDK
        uses: ./.github/actions/setup-gradle-jdk
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -Porg.gradle.java.installations.auto-download=false
            -PjavaToolchainVersion=${{ matrix.jdk }}
            -Dplatform.tooling.support.tests.enabled=true
            -Dscan.tag.JDK_${{ matrix.jdk }}
            javaToolchains
            build
      - name: Upload Test Distribution trace files
        uses: actions/upload-artifact@v2
        with:
          name: Test Distribution trace files
          path: '**/build/test-results/*/trace.json'
