name: Cross-Version

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - '*'

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [12, 13, 14]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    container: "junitteam/build:${{ matrix.jdk }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          ./gradlew --version
          ./gradlew --scan --no-parallel --warning-mode=all -Dplatform.tooling.support.tests.enabled=true -PjavaHome=$ADDITIONAL_JDK build
