name: Cross-Version

on:
  push:
    branches:
      - master
      - 'releases/*'
  pull_request:
    branches:
      - '*'

env:
  ORG_GRADLE_PROJECT_junitBuildCacheUsername: ${{ secrets.BUILD_CACHE_USERNAME }}
  ORG_GRADLE_PROJECT_junitBuildCachePassword: ${{ secrets.BUILD_CACHE_PASSWORD }}

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [12, 13, 14, 15]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    container: "junitteam/build:${{ matrix.jdk }}"
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Gradle Enterprise credentials
        run: |
          mkdir -p ~/.gradle/enterprise/
          echo "${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}" > ~/.gradle/enterprise/keys.properties
      - name: Test
        run: |
          ./gradlew --version
          ./gradlew --scan --no-parallel --warning-mode=all -Dplatform.tooling.support.tests.enabled=true -PjavaHome=$ADDITIONAL_JDK build
